# Generated by Django 5.2.1 on 2025-05-15 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad', models.CharField(max_length=200)),
                ('propiedad_id', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_contacto', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
