# Generated by Django 5.2.1 on 2025-05-15 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('baños', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('tamaño', models.IntegerField()),
                ('tamaño_lote', models.DecimalField(decimal_places=1, max_digits=5)),
                ('foto_principal', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('foto_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('foto_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('foto_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('foto_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('foto_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('foto_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('esta_publicado', models.BooleanField(default=True)),
                ('lista_dato', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
    ]
