# Generated by Django 5.2.1 on 2025-05-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propiedad_remove_listing_realtor'),
        ('realtors', '0004_dueño_delete_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.dueño'),
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
