# Generated by Django 5.2.1 on 2025-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_propiedad_dueño_delete_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='departamento',
            field=models.CharField(choices=[('AMA', 'Amazonas'), ('ANT', 'Antioquia'), ('ARA', 'Arauca'), ('ATL', 'Atlántico'), ('BOL', 'Bolívar'), ('BOY', 'Boyacá'), ('CAL', 'Caldas'), ('CAQ', 'Caquetá'), ('CAS', 'Casanare'), ('CAU', 'Cauca'), ('CES', 'Cesar'), ('CHO', 'Chocó'), ('COR', 'Córdoba'), ('CUN', 'Cundinamarca'), ('DC', 'Bogotá, D.C.'), ('GUA', 'Guainía'), ('GUV', 'Guaviare'), ('HUI', 'Huila'), ('LAG', 'La Guajira'), ('MAG', 'Magdalena'), ('MET', 'Meta'), ('NAR', 'Nariño'), ('NSA', 'Norte de Santander'), ('PUT', 'Putumayo'), ('QUI', 'Quindío'), ('RIS', 'Risaralda'), ('SAN', 'Santander'), ('SAP', 'San Andrés y Providencia'), ('SUC', 'Sucre'), ('TOL', 'Tolima'), ('VAC', 'Valle del Cauca'), ('VAU', 'Vaupés'), ('VID', 'Vichada')], max_length=3),
        ),
    ]
