# Generated by Django 5.2.1 on 2025-05-15 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propiedad_remove_listing_realtor'),
        ('realtors', '0003_alter_realtor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('descripcion', models.TextField(blank=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(blank=True, default=datetime.datetime.now)),
                ('fecha_inicio', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
